### ISSUE TITLE
Maps of projected walleye and bass lakes over time

### ISSUE THREAD

**Issue by gjahansen2** [USGS-VIZLAB/climate-fish-habitat#10]
Gretchen provides data on probability of each species in each GCM and time period, plus threshold separating good from bad for each species.

**Comment by gjahansen2** [comment]
@lawinslow 
Data here: https://drive.google.com/open?id=0BwCnuHTL_uP9NXZnOTZEVHdUMGM
future_lmb_projected_probability.csv
future_wae_projected_probability

These are in "long" format, with a column for time period and model. Probability is listed, plus a binary variable describing walleye recruitment success/failure (1/0) and bass high/low abundance (0/1)

**Comment by jordansread** [comment]
@gjahansen2 and @lawinslow thoughts on using the sankey here instead but making it interactive?

**Comment by gjahansen2** [comment]
Yes. I like it.

**Comment by lawinslow** [comment]
Sure, what interaction mode are you thinking? Also, you'll probably have to take it on if you want to go SVG'd interactive.

**Comment by jordansread** [comment]
Ok, I can take this if we want to go w/ the sankey

**Comment by jordansread** [comment]
#28
