### ISSUE TITLE
Add helper note "click on a lake to get more information"

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#100]

**Comment by jordansread** [comment]
on the explore map

**Comment by jordansread** [comment]
or a splash screen on top of the map when you enter. @gjahansen2 has ideas for text

**Comment by gjahansen2** [comment]
I need some feedback on this. 

Text for screen when you enter the map site:

# PLEASE READ THIS FIRST!

## Welcome to the interactive map for viewing current and future predicted conditions for walleye and largemouth bass in Wisconsin lakes!

### Lakes are colored based on predicted habitat conditions for each species. Double-click on a lake for more information.

• "Walleye lakes” are predicted to have habitat conditions capable of supporting naturally reproducing walleye populations (>49% probability) but not high largemouth bass abundance (<49% probability).
• "Bass lakes” are predicted to have the habitat conditions capable of supporting high largemouth bass abundance (>49% probability) but not naturally reproducing walleye populations (<49% probability).
• "Coexistence" lakes are predicted have the habitat conditions capable of supporting both naturally reproducing walleye populations (>49% probability) and high largemouth bass abundance (>49% probability).
• "Neither" lakes are predicted to support neither naturally reproducing walleye populations (<49% probability) nor high largemouth bass abundance (<49% probability).

### Double-clicking on a lake will show specific predicted probabilities. It is important to note that some lakes classified as not supporting a given species may in fact contain that species. Also note that some lakes will switch categories based on very small changes in predicted probabilities.

Predictions of species dominance are available for three time periods - contemporary conditions (1989-2014), and two future periods (2040-2064, and 2065-2089).

## Disclaimer: Lake-specific predictions are based on modeled water temperature data and other lake conditions. Future projections are based on a high-end climate change scenario, and are uncertain. Generally, interpreting projections for a specific lake should be done with caution as many factors were not considered (e.g. other fish species, land-use changes, stocking). Projected shifts from a “Walleye lake” to a “Bass lake” should be viewed as a shift in the habitat conditions and fish community as opposed to a certain future state where Largemouth Bass overpopulate the lake.

**Comment by gjahansen2** [comment]
Can we make the bullets colored to match the lake category colors? @jread-usgs

**Comment by gjahansen2** [comment]
Can we change the legend to match the above definitions (walleye lakes and bass lakes as opposed to walleye dominant and bass dominant)? @jread-usgs

**Comment by jordansread** [comment]
Looks great. We'll mock something up for this

**Comment by jordansread** [comment]
@mwernimont can you create this splash screen on the "explore" map that ends up here: http://localhost:8000/explore/map.html
?

**Comment by mwernimont** [comment]
@jread-usgs Is this still an issue?

**Comment by jordansread** [comment]
this is complete. Thanks @mwernimont
