### ISSUE TITLE
recreate the map w/ the new data

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#102]
Shapefile is now outdated

**Comment by jordansread** [comment]
Done. @gjahansen2 please review the map

![image](https://cloud.githubusercontent.com/assets/2349007/17467686/8f3596b0-5ce6-11e6-98ff-4d941c3acc70.png)

**Comment by gjahansen2** [comment]
Why is Petenwell missing? are there 2148 lakes in the map?

**Comment by jordansread** [comment]
I will look into it

**Comment by jordansread** [comment]
fixed. Can you verify @gjahansen2 ?

**Comment by gjahansen2** [comment]
looks good to me!
