### ISSUE TITLE
Add economic impact of fishery

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#112]
@gjahansen2 can you think of how/where to work this in?

**Comment by gjahansen2** [comment]
I think in the bullet points above the walleye/bass trends graph. Add this as the first bullet:
- Recreational fishing in Wisconsin is valued at over $2 billion annually.

(if we need a source/footnote it is http://asafishing.org/uploads/2011_ASASportfishing_in_America_Report_January_2013.pdf)

**Comment by gjahansen2** [comment]
see #120

**Comment by jordansread** [comment]
in #122
