### ISSUE TITLE
build sankey toggle into svg

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#116]
right now we do an image swap. We should handle it within a single svg so it is standalone and smoother. 

This is pending us actually wanting to move ahead w/ showing acreage, which I will defer to @gjahansen2 on. Won't work on this unless we are going to keep it.

**Comment by gjahansen2** [comment]
Let's see what WDNR staff thinks

**Comment by jordansread** [comment]
I think this is not going to happen. Working on making the toggle better @thongsav-usgs
