### ISSUE TITLE
Edit disclaimer and add FAQ to map site

### ISSUE THREAD

**Issue by gjahansen2** [USGS-VIZLAB/climate-fish-habitat#121]

**Comment by gjahansen2** [comment]
# PLEASE READ FIRST

## Welcome to the interactive map for viewing current and future predicted conditions for walleye and largemouth bass in Wisconsin lakes!

Lakes are colored based on predicted habitat conditions for each species. Double-click on a lake for more information.

Predictions of species dominance are available for three time periods - contemporary conditions (1989-2014), and two future periods (2040-2064, and 2065-2089).

"Walleye lakes” are predicted to have habitat conditions capable of supporting naturally reproducing walleye populations (>49% probability) but not high largemouth bass abundance (<49% probability).
"Bass lakes” are predicted to have the habitat conditions capable of supporting high largemouth bass abundance (>49% probability) but not naturally reproducing walleye populations (<49% probability).
"Coexistence" lakes are predicted have the habitat conditions capable of supporting both naturally reproducing walleye populations (>49% probability) and high largemouth bass abundance (>49% probability).
"Neither" lakes are predicted to support neither naturally reproducing walleye populations (<49% probability) nor high largemouth bass abundance (<49% probability).

## Disclaimer: Lake-specific predictions are based on modeled water temperature data and other lake conditions such as lake size. Future projections are based on a high-end climate change scenario, and are uncertain. Generally, interpreting projections for a specific lake should be done with caution as many factors were not considered (e.g. other fish species, land-use changes, stocking). Projected shifts from a “Walleye lake” to a “Bass lake” should be viewed as a shift in the thermal habitat conditions and fish community as opposed to a certain future state where Largemouth Bass overpopulate the lake.

**Comment by gjahansen2** [comment]
^^edited from current version

**Comment by jordansread** [comment]
covered in #122
