### ISSUE TITLE
"read more" button for more info on GDD

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#123]
In the section under "Can you draw...", most of the first paragraph explains what GDD is. Let's keep the first sentence as is, and make the rest of that paragraph hidden unless the viewer clicks on something to expand. "More information on growing degree days" or "What are growing degree days" as a clickable button?

![image](https://cloud.githubusercontent.com/assets/2349007/18214347/2ac9d43a-7112-11e6-9892-ed4860268e9f.png)

**Comment by jordansread** [comment]
@mwernimont if you can handle this one too

**Comment by mwernimont** [comment]
@jread-usgs #139
