### ISSUE TITLE
figure suggestion from gretchen

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#124]
"On x-axis label of the 'you draw it' figure, add Lake Temperature to the label above Growing degree days (make the Lake temperature label bigger than the GDD label)."

![image](https://cloud.githubusercontent.com/assets/2349007/18216080/341eb67e-711a-11e6-908f-d3f1b2c68e30.png)

@gjahansen2 where does this text fit?

**Comment by jordansread** [comment]
OK, now I understand. @gjahansen2 I will need clarification as to whether this is a priority before the release, since that is really soon(!) and there are a lot of loose ends to clear up

**Comment by gjahansen2** [comment]
Not a priority, I think other stuff is more important!
