### ISSUE TITLE
Can we have a small form at the end of this viz?

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#127]
Not sure about paperwork reduction act, etc, but it would be helpful to collect some user data:

Who are you (general public, manager, researcher, etc...)
Did you learn more about sport fish and climate change?
What section did you find most useful (list options)
Others?

**Comment by lindsayplatt** [comment]
See issue in VIZLAB: https://github.com/USGS-VIZLAB/vizlab/issues/46
