### ISSUE TITLE
change bass values to be more intuitive

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#128]
change bass values to be more intuitive rather than standardized relative abundance (Gretchen will send new data)

Also, note the trickle down effect of text and captions in the viz. We'll need to comb it if we change the units and make sure we are up to date w/ the figure.

**Comment by gjahansen2** [comment]
Is this worth doing, given the trickle down changes that are required all around, and that it is not straightforward how to do this since the current scale is output from a mixed effects model that combines two gear types?

**Comment by jordansread** [comment]
skipping this.
