### ISSUE TITLE
Minor updates before release

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#130]
- [x] link to paper - JR (if they follow the pattern, should be http://onlinelibrary.wiley.com/doi/10.1111/gcb.13462/full)
- [x] link to data release - Emily
- [x] link to github - Emily
- [x] social media sharing icons/links - Laura & Marty
- [x] link to VIZLAB organization - Emily
- [x] create the JSON LD indexed content stuff (not sure what this is called, but we register site information, icon, title, etc). Did this for Lower CO viz - Emily & JW
- [x] alt text for images! Lindsay
- [x] 508 compliance sweep - Lindsay

**Comment by jordansread** [comment]
@mwernimont can you take a swing at the social media sharing links/icons? twitter and github are the two that come to mind.

**Comment by jordansread** [comment]
@lindsaycarr how are the alt text images coming?

**Comment by lindsayplatt** [comment]
alt text for images PR: #149
