### ISSUE TITLE
IE bug on map 

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#132]
I don't have IE, but apparently, the header to this table is lost on IE:
![image](https://cloud.githubusercontent.com/assets/2349007/18247391/e58d8128-7337-11e6-9edb-f98010644351.png)

**Comment by lawinslow** [comment]
Here's how it looks in IE
![image](https://cloud.githubusercontent.com/assets/347600/18256035/71503344-7375-11e6-81a7-549534ab88d5.png)

**Comment by jordansread** [comment]
Thanks Luke. Pleasantly surprised this is our only IE issue that was noticed.

**Comment by jordansread** [comment]
@mwernimont can you take this one too?

**Comment by jordansread** [comment]
This was resolved in a PR today.
