### ISSUE TITLE
Add FAQ to map

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#133]
"a button on the map that makes them pop out?"

Waiting on @gjahansen2 for FAQ text.

**Comment by gjahansen2** [comment]
[Frequently Asked Questions.docx](https://github.com/USGS-VIZLAB/climate-fish-habitat/files/455347/Frequently.Asked.Questions.docx)

**Comment by mwernimont** [comment]
@jread-usgs PR here #134
