### ISSUE TITLE
Set up CI jenkins jobs

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/climate-fish-habitat#135]

**Comment by jiwalker-usgs** [comment]
one issue I just thought of for the CI is that we don't check in the target directory, so we will need a way to get the output to Jenkins

**Comment by lawinslow** [comment]
Can it be built on Jenkins? Or is it a combined manual/automated process? 

Otherwise, we could just check-in the target directory.

**Comment by jiwalker-usgs** [comment]
It could be built in Jenkins, the setup might be a bit involved though.

**Comment by lawinslow** [comment]
R > command not found. 

Ok, I suggest we opt for checking in the target directory for now.

**Comment by ldecicco-USGS** [comment]
Me too
