### ISSUE TITLE
Visualization of contemporary lake temperature trends

### ISSUE THREAD

**Issue by lawinslow** [USGS-VIZLAB/climate-fish-habitat#15]

**Comment by lawinslow** [comment]
@jread-usgs @gjahansen2 

Ideas/feedback needed here. 

One can go a pretty simple route. State-wide lake average summertime surf water temps. Based on WiLMA modeling. The timeseries is noisy but there is a trend to it. Doesn't pop like I usually would want a vis to.

![wi_avg_jas](https://cloud.githubusercontent.com/assets/347600/15944257/65130844-2e52-11e6-8b32-4707bbcb2ac9.png)

Another thing we talked about is two maps, before/after (1980's, 2000's, or something like that). Overall differences aren't huge. Cross-lake differences are larger making such comparison challenging. 
![1980s_jas_map](https://cloud.githubusercontent.com/assets/347600/15944328/bdffc74e-2e52-11e6-8715-a405c5dc8a19.png)
![2000s_jas_map](https://cloud.githubusercontent.com/assets/347600/15944329/bdffe58a-2e52-11e6-9aa3-2cc3e6269d30.png)

Thoughts?

**Comment by gjahansen2** [comment]
What about maps of change, or percent change? Like this, but with a metric
that makes sense to people (percent increase?) or if you base it on summer
average temperatures, you could say degree increase
[image: Inline image 1]

On Thu, Jun 9, 2016 at 2:59 PM, Luke Winslow notifications@github.com
wrote:

> @jread-usgs https://github.com/jread-usgs @gjahansen2
> https://github.com/gjahansen2
> 
> Ideas/feedback needed here.
> 
> One can go a pretty simple route. State-wide lake average summertime surf
> water temps. Based on WiLMA modeling. The timeseries is noisy but there is
> a trend to it. Doesn't pop like I usually would want a vis to.
> 
> [image: wi_avg_jas]
> https://cloud.githubusercontent.com/assets/347600/15944257/65130844-2e52-11e6-8b32-4707bbcb2ac9.png
> 
> Another thing we talked about is two maps, before/after (1980's, 2000's,
> or something like that). Overall differences aren't huge. Cross-lake
> differences are larger making such comparison challenging.
> [image: 1980s_jas_map]
> https://cloud.githubusercontent.com/assets/347600/15944328/bdffc74e-2e52-11e6-8715-a405c5dc8a19.png
> [image: 2000s_jas_map]
> https://cloud.githubusercontent.com/assets/347600/15944329/bdffe58a-2e52-11e6-9aa3-2cc3e6269d30.png
> 
> Thoughts?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/15#issuecomment-225008725,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6kaidEQ7rFlIflj_SJZQ8mVndvJaks5qKHCjgaJpZM4IyWC_
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by lawinslow** [comment]
Yeah, I like that. But it lacks the interactive features that @jread-usgs craves

**Comment by lawinslow** [comment]
Though I don't think I'll use % change. I'll play around with just degC change.

**Comment by jordansread** [comment]
degC change seems fine, and we don't need it to be interactive. Perhaps just a smaller static figure that is inset within the text?

**Comment by lawinslow** [comment]
![contemporarylaketrends](https://cloud.githubusercontent.com/assets/347600/16056480/5114f22a-323b-11e6-995d-66414655644c.png)

**Comment by lawinslow** [comment]
Thinking something like this, though I hate those hot great lake neighbor lakes

**Comment by jordansread** [comment]
see #26
