### ISSUE TITLE
Facebook share not working

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/climate-fish-habitat#182]
I can't figure out why. @mwernimont ?

Same code seems to work on blogs.

**Comment by mwernimont** [comment]
@ldecicco-USGS So when I click on the facebook button it opens up a face book popup in the upper left of my screen, is that not the intended functionality?

**Comment by ldecicco-USGS** [comment]
That is, but the link is saying 404 Not found, and no picture:

![image](https://cloud.githubusercontent.com/assets/1105215/18352273/5aa3f4c0-75a3-11e6-92cd-6fae86037951.png)

Whereas in the blogs, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1105215/18352295/76219018-75a3-11e6-9e66-be7a819dd861.png)

**Comment by mwernimont** [comment]
`http://www.facebook.com/sharer.php?src=bm&u={{ permalink }}&t={{ title }}"`

I'm assuming it has something to do with the permalink address? I don't really know what thats pointing to. Maybe its different address when pointing from another website?

**Comment by ldecicco-USGS** [comment]
yeah - when I View Source, the vizzies show:

"http://www.facebook.com/sharer.php?src=bm&u=https://owi.usgs.gov/vizlab/microplastics/&t=Microplastics in our Nation's Waterways"

and the blog show:

"http://www.facebook.com/sharer.php?src=bm&u=https%3a%2f%2fowi.usgs.gov%2fblog%2fplotFlowConc%2f&t=EGRET%20plotFlowConc%20using%20ggplot2"

I tried for a long time to force a url-encode into the vizzies, but never got it to work. But, I don't think that's the only problem, because no where in that url indicates anything about the picture, and really the title in the URL of the blog doesn't match the title that the facebook sharelink is showing, so clearly it's pulling that from some other tag.

**Comment by mwernimont** [comment]
@ldecicco-USGS Where does this all happen? Like where do we have the {{permalink}} code? like what fills in that

**Comment by ldecicco-USGS** [comment]
So the top line of the siteText.yaml has:
permalink: https://owi.usgs.gov/vizlab/climate-change-walleye-bass/

I assume it's the same process as any other text from the siteText to the html...(all magic to me...)
