### ISSUE TITLE
Future Climate figure

### ISSUE THREAD

**Issue by lawinslow** [USGS-VIZLAB/climate-fish-habitat#20]
![futureclimatescenarios](https://cloud.githubusercontent.com/assets/347600/16056518/75d29ae0-323b-11e6-8082-73a89dab06b5.jpg)
@jread-usgs @gjahansen2 thoughts? I've got the original data on hand, so we can do what we want.

**Comment by gjahansen2** [comment]
But these aren't the scenarios/models used for this analysis, right?

**Comment by lawinslow** [comment]
No, but they are the more up to date ones. Torn between "it fulfills the message" and "we should use what we actually use". hmmm

**Comment by lawinslow** [comment]
Let me see what I can find. Raw data for the older sims is harder to find.

**Comment by jordansread** [comment]
#27
