### ISSUE TITLE
section "walleyeDecline" figure content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#24]
MVP:
simple mouseover line plots with the contemporary increase in LM Bass and decrease in Walleye for WI

Nice-to-have:
Animate line drawings through time

**Comment by jordansread** [comment]
@gjahansen2 using the new residuals data, but should this be exceeding 1? 

this is bass:
![image](https://cloud.githubusercontent.com/assets/2349007/16166342/1d61f988-34b0-11e6-8f73-b6e90ff6f3dd.png)

**Comment by gjahansen2** [comment]
Yes, its ok that it exceeds 1.

**Comment by gjahansen2** [comment]
Can we add a trendline to make it more clear that this is increasing?

**Comment by jordansread** [comment]
yes

**Comment by jordansread** [comment]
I also want to combine these two into a single fig I think.

**Comment by jordansread** [comment]
As with above, I was thinking both trends on the same fig, and as it animates through time, the number of wally/bass in the sides of the fig change to show the shifts in dominance. Something like this but with them in a different place (more out of the way), more fish that are smaller, and maybe proportional in number to the trends. 

![image](https://cloud.githubusercontent.com/assets/2349007/16366687/87378580-3be0-11e6-9977-700a5b8b498c.png)

**Comment by jordansread** [comment]
@lindsaycarr is combining the two into one figure. I will work on adding a legend later (one that will probably be shared w/ fig 2)

**Comment by jordansread** [comment]
w/ @lindsaycarr 's work:

![image](https://cloud.githubusercontent.com/assets/2349007/16393408/4726f9ee-3c76-11e6-8a45-af7df45f5f49.png)

@gjahansen2 I don't know that relative abundance works well for this since the baseline populations for these two are so different
Should the numbers be weighted in some way based on how many lakes these two appear in?

**Comment by jordansread** [comment]
drawing in the lines w/ the fish moving left and right:
![image](https://cloud.githubusercontent.com/assets/2349007/16474404/24a0326a-3e3c-11e6-94a1-2a959e748d6a.png)

**Comment by gjahansen2** [comment]
Is this walleye adult population? I think the trend would be more clear with the recruitment data. But the numeric scale might be different (2 y-axes, perhaps?). I like the fish outlines!

**Comment by jordansread** [comment]
@gjahansen2 can you do a simple mock-up of what you are thinking? We are using the data that you suggested (the BLAM) for both. I can point to the files that we are using if that would be helpful.

**Comment by gjahansen2** [comment]
BLUP?

**Comment by gjahansen2** [comment]
I just mean that the adult walleye data do not show the same decline as the walleye recruitment data. Plus, walleye recruitment is what we are measuring anyway. So why not plot recruitment for walleye? But it might not be on the same scale as the bass data, so if you want them on the same plot, you might need two y axes

**Comment by gjahansen2** [comment]
![image](https://cloud.githubusercontent.com/assets/19436778/16492736/63a28f28-3ea8-11e6-8647-ed280db19d5f.png)

**Comment by gjahansen2** [comment]
Note that I removed 2015 from the bass data because i learned it is incomplete

**Comment by jordansread** [comment]
OK, I see. Thanks

**Comment by jordansread** [comment]
@gjahansen2 here is what I have now:

![image](https://cloud.githubusercontent.com/assets/2349007/16591171/405e1130-42a0-11e6-8b53-ad33c93b72ec.png)

**Comment by gjahansen2** [comment]
That is better for sure. What do you think about trendlines? Maybe just as
faint, transparent or dashed lines, but to give the viewer the stronger
sense of walleye down and bass up.

On Tue, Jul 5, 2016 at 11:04 AM, Jordan S Read notifications@github.com
wrote:

> @gjahansen2 https://github.com/gjahansen2 here is what I have now:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/2349007/16591171/405e1130-42a0-11e6-8b53-ad33c93b72ec.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/24#issuecomment-230523308,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6kKwJRI5Spx9dpvtG6ZJHzZRQK33ks5qSoCWgaJpZM4I2WcK
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
I have mixed thoughts on the trendlines. I think they are clear, but the animation of the two populations moving from right to left also does that. I hoped to keep the clutter down, which is the only reason I am skipping the trendlines for now. I also need to add a mouseover legend for the values too, so I want to protect the space if possible. 

Alternative idea @gjahansen2, we could add the dashed trendline when the animation is complete?

**Comment by jordansread** [comment]
you just doing an `lm()` of time vs value for that line?

**Comment by gjahansen2** [comment]
I like the idea of adding trendlines after the animation is complete. I
hadn't seen it in animated form yet, so maybe filling in the two
populations over time will solve the issue. Yes, just regression line over
time.

On Tue, Jul 5, 2016 at 11:18 AM, Jordan S Read notifications@github.com
wrote:

> you just doing an lm() of time vs value for that line?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/24#issuecomment-230526912,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6qlEwfXeTR8dDd_Fr9fSFkQFQsnpks5qSoO5gaJpZM4I2WcK
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
@gjahansen2 w/ trendline:
![image](https://cloud.githubusercontent.com/assets/2349007/16690362/2b9eacc4-44ed-11e6-89ba-a4688d0e7891.png)

**Comment by jordansread** [comment]
I still don't have the trend line appearing after the animation. I will take care of that later.

**Comment by jordansread** [comment]
now discussed in #75
