### ISSUE TITLE
section "lakeWarming" figure content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#26]
A visual that covers the concept that lakes have warmed in the contemporary period

MVP: map of °F delta for 1980-present

![image](https://cloud.githubusercontent.com/assets/2349007/16081460/1cb2da9a-32d3-11e6-9b7a-d32c094bb8c1.png)

nice-to-have: ???

**Comment by jordansread** [comment]
@lawinslow what about your observed trends (Winslow ea 2015; S1; but only the 3,000+ pairs) figure changed to a delta °C? 
![image](https://cloud.githubusercontent.com/assets/2349007/16181012/b408e568-3659-11e6-976b-14ab9acebe6a.png)

**Comment by gjahansen2** [comment]
ooh, I like that.

**Comment by lawinslow** [comment]
Could do that, let's see what the it looks like with sparse dots.

**Comment by jordansread** [comment]
With a smaller number of sites, the mouseover could actually reveal a small inset plot for that site with the actual time series water temp data. A "nice-to-have"?

**Comment by jordansread** [comment]
@lawinslow any plans on this fig?

**Comment by lawinslow** [comment]
No major plans. We can try the empirical approach, but I don't have the time to make it interactive.

**Comment by jordansread** [comment]
OK, please give it a shot.

**Comment by jordansread** [comment]
as per #101 , we might want to keep this to °C unless we are changing the degree day figs to °F degree days. Thoughts?

**Comment by gjahansen2** [comment]
See comments on #101 in response.   But, I think we still were hoping to have a map based on empirical trends, yes?

**Comment by jordansread** [comment]
Update: looks like Wiley moved the release up to September 7th. @lawinslow what is the plan w/ this figure? re-create with °F?

**Comment by gjahansen2** [comment]
I just got a new version of the dev site but this figure still looks the same. Are we going to have a map of observed temperature trends to avoid the Lake Michigan weird warming effect? @lawinslow @jread-usgs

**Comment by lawinslow** [comment]
No, I'd rather not do observed. Looking through it, uncertainty is extremely high for any single lake trend and so gives a false sense of uncertainty (and individual really high trends in lakes).
