### ISSUE TITLE
section "futureWarming" figure content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#27]
A visual that covers the concept that lakes are expected to continue to warm in the 21st century

MVP: a mouseover line plot with the GCM runs used in this study and the A2 scenario for air temperatures
similar to 

![image](https://cloud.githubusercontent.com/assets/2349007/16205592/1cb3598c-36ea-11e6-99c7-f94932375c58.png)

nice-to-have: ???

**Comment by jordansread** [comment]
@lawinslow is your fig going to be static or interactive?

**Comment by jordansread** [comment]
Should we somehow highlight (subtly?)  the time periods in "futureSuitability" on this fig? 
those periods are:
![image](https://cloud.githubusercontent.com/assets/2349007/16688513/02f1d034-44e4-11e6-845b-6a8c59d53a9e.png)

**Comment by gjahansen2** [comment]
Also, as per our discussion earlier today, what if we had a figure like this, showing the magnitude of warming (as colors, size of dots, or both) as a function of two critical lake variables (like lake size and clarity, or maybe depth):
![image](https://cloud.githubusercontent.com/assets/19436778/16698273/1cf1886a-4513-11e6-99f2-c5d059c44df1.png)

**Comment by gjahansen2** [comment]
![image](https://cloud.githubusercontent.com/assets/19436778/16700274/cfae75d4-451e-11e6-8ca4-472ea458e4f8.png)

**Comment by gjahansen2** [comment]
Maybe this won't work as nicely as I thought when using all lakes. Perhaps picking a representative set would work though.

**Comment by jordansread** [comment]
interesting pattern though

**Comment by jordansread** [comment]
@lawinslow gretchen has a bunch of ideas for this section.

**Comment by gjahansen2** [comment]
![median_gdd_range_3lakes_highlighted](https://cloud.githubusercontent.com/assets/19436778/16818798/31134ec8-490f-11e6-85d6-d23f3bac2822.png)

**Comment by gjahansen2** [comment]
Or some other way of showing variability in lake responses to warming.

**Comment by lawinslow** [comment]
@gjahansen2 trying the above figure style. Do you want the lake names on there? Are those lakes you listed the ones you want (have you checked values) otherwise, I found good spread on Trout/Mendota/Green lakes.

**Comment by lawinslow** [comment]
![futurewarmingfig](https://cloud.githubusercontent.com/assets/347600/17187777/3e641d0e-5400-11e6-9774-fbc5a2c6074c.png)

**Comment by gjahansen2** [comment]
That looks great!

**Comment by lawinslow** [comment]
![futurewarmingfig](https://cloud.githubusercontent.com/assets/347600/17189579/b31a0d28-5407-11e6-95c6-2c1869adf69d.png)

**Comment by lawinslow** [comment]
nah, I prefer this
![futurewarmingfig](https://cloud.githubusercontent.com/assets/347600/17189630/eedbadc6-5407-11e6-9377-3faf1d41849e.png)

**Comment by jordansread** [comment]
Do we need an inset map showing where these lakes are?

**Comment by lawinslow** [comment]
Yeah, not a bad idea. Though I did try to pick relatively recognizable lakes. Even I know them, so I figured anyone interested in fishing/lakes would probably be familiar with them.

**Comment by jordansread** [comment]
yeah, I think it is best for us to assume a good part of the audience to not be from WI.

**Comment by gjahansen2** [comment]
1. Agree with Jordan - we need to identify something about where these lakes are, and why we picked them (to show the range of lake responses).
2. I liked having some kind of light gray/transparent bar behind the dots, like in my version (which was real data, BTW). So there is an indication of the range of lake responses to climate, and we are highlighting a few well known lakes.
3. I liked the old figure showing air temperature change - I think the new figure should be in addition to that old one, rather than in place of.

**Comment by jordansread** [comment]
Yeah, I agree w/ `3` that the air temp fig is important context for the warming scenario (that it is the more extreme)

**Comment by jordansread** [comment]
From Gretchen `change legend labels on future air temperature projections graph to be "High greenhouse gas emissions (A2)" and "Low greenhouse gas emissions (B1)".`
