### ISSUE TITLE
section "futureSuitability" figure content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#28]
A visual that covers changing wally/bass lakes into the future

MVP: Sankey figure w/ mouseovers?
![image](https://cloud.githubusercontent.com/assets/2349007/16215979/98471c5e-372c-11e6-9ae5-0817bbfb739e.png)

nice-to-have: a nice slider map of changing lakes? a map linked to the sankey?

**Comment by jordansread** [comment]
if we use the sankey, we need to be consistent throughout the viz with what colors are used for Wally and Bass

**Comment by jordansread** [comment]
@lindsaycarr see the figure above? It is static right now and it would be great to hear your thoughts on good things to add when making it interactive. Do you have ideas?

**Comment by lindsayplatt** [comment]
I saw your note about a map - I think it would be cool to have points on the map highlight at the same time the corresponding the species sankey bars do. Plus, whatever piece of the bar your mouse is over (walleye, coexistence, bass, or neither) should highlight any lines coming off of it leading to the next one. You also say a "slider map" which I assume is for the different years. When you move your mouse to the next category of years in the sankey, it should switch the map over, too (as well as highlight the lakes with the matching dominant species). Not sure if this is already what you were thinking

**Comment by jordansread** [comment]
@lindsaycarr what you you think about the sankey lines ending w/ the color of the bin they are merging in vs not:

![image](https://cloud.githubusercontent.com/assets/2349007/16182161/82286a78-3668-11e6-9f57-5840dbcd4f73.png)

vs 

![image](https://cloud.githubusercontent.com/assets/2349007/16182163/8e1f9202-3668-11e6-8154-0ee84f67f557.png)

(note the first has a gradient, the second does not)

**Comment by lindsayplatt** [comment]
@jread-usgs I think that's pretty cool!

**Comment by jordansread** [comment]
@lindsaycarr the gradient?

@gjahansen2 do you have an opinion on this one too?

**Comment by lindsayplatt** [comment]
@jread-usgs yes the gradient

**Comment by jordansread** [comment]
from Gretchen for this fig:
- [ ] Will there be a place to define what "walleye dominant" and "bass dominant" mean? Is it better to do that within the interactive figure, or within a caption or something? Definitely need to at least say somewhere that "bass" refers to largemouth bass.
- [ ] For "Neither" and "Coexistence" lakes, can we change the text to be more understandable? "43 lakes where both walleye and bass co-exist". "660 lakes where neither walleye or bass are supported". Similarly, "498 lakes shift from supporting neither species to bass dominant".
- [ ] In the transitions from mid- to late-century, can we change the text to be clear that these are additional lakes moving between categories? E.g., for walleye lakes transitioning to bass lakes, "7 additional lakes shift from walleye dominant to bass dominant".

**Comment by jordansread** [comment]
Also, should "Neither" be a bin category? Think about this: If we remove "Neither" and have the flow lines come out of a gradient transition from nothing to the color of the bin it is moving into, is that more intuitive, or less intuitive? Likewise, when dropping out of bass into neither, the flow line would start red and fade to totally transparent.

**Comment by gjahansen2** [comment]
I like the gradient.

I am not sure I get what it would look like without a "neither' bin. Where would the lakes that are becoming bass lakes (from neither) come from? Where would the walleye lakes that are losing walleye and not gaining bass go to?

**Comment by jordansread** [comment]
here's is kind of what it would look like. I don't think I like it. Seems more confusing
![image](https://cloud.githubusercontent.com/assets/2349007/16209455/bbfd4dba-36fc-11e6-82a1-55c705911aa6.png)

**Comment by gjahansen2** [comment]
I like having the 'neither' bin.

On Mon, Jun 20, 2016 at 3:36 PM, Jordan S Read notifications@github.com
wrote:

> here's is kind of what it would look like. I don't think I like it. Seems
> more confusing
> [image: image]
> https://cloud.githubusercontent.com/assets/2349007/16209455/bbfd4dba-36fc-11e6-82a1-55c705911aa6.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/28#issuecomment-227261539,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6iOCiWrnk75VryCBD8hcX7fh70RHks5qNvnFgaJpZM4I2XEL
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
me "neither" loolz

**Comment by jordansread** [comment]
@gjahansen2 for your comments above ☝️ 

"Will there be a place to define what "walleye dominant" and "bass dominant" mean?" `yes, in the figure caption I assume`

"For "Neither" and "Coexistence" lakes, can we change the text to be more understandable?" you're recommendations make me think we might need special text for each one. `Right now I built it programmatically, so it is based on the combinations of the bins and the numbers of lakes. If we want special phrases, we might need to make a special one for each flow between the bins. You think it is important to do it? If so, let me know and I can work in a way to do it.`

"In the transitions from mid- to late-century, can we change the text to be clear that these are additional lakes moving between categories?"
`same answer as 2`

**Comment by gjahansen2** [comment]
Hmm...I hate to say yes it is super important right now, when there is so much other stuff that is probably more important. So let's just wait and see how it all unfolds, and maybe get some feedback from others once it is all together in a viz that we are ready to show to someone else.

**Comment by jordansread** [comment]
@gjahansen2 

``` yaml
futureSuitability-fig:
  Walleye: >-
    %s Walleye dominant lakes
  Bass: >-
    %s Bass dominant lakes
  Neither: >-
    %s lakes where neither walleye or bass are supported
  Coexistence: >-
    %s lakes where both walleye and bass co-exist
  Neither-Bass: >-
    %s lakes now support bass
  Neither-Walleye: >-
    %s lakes now support walleye
  Walleye-Coexistence: >-
    %s walleye lakes now support walleye and bass
  Neither-Coexistence: >-
    %s lakes now support walleye and bass
  Bass-Neither: >-
    %s bass lakes now support neither species
  Walleye-Neither: >-
    %s walleye lakes now support neither species
```

I added some text to have those flows and bins make more sense, but it was incomplete and probably not the exact wording you would have chosen. The pattern ☝️ is `bin` (one word, like "Walleye") or `flow`, left to right ("Walleye-Bass" means moving from wally to bass). The `%s` is where the number of lakes is subbed in. 

If you have edits, you can comment here and I can modify them. You can add new ones too - the two word combinations that don't show up here use the default wording that you have already seen. 
Added text edits to #49

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/16252110/24da84ac-37f1-11e6-99cf-8cb2b33230bf.png)
e.g. 

``` yaml
Neither-Bass: >-
    %s lakes now support bass
```

**Comment by gjahansen2** [comment]
This is better. The only hang up I have at this point is the use of the word "now" to describe future scenarios. Can we change to "predicted to"? So "120 lakes predicted to support bass"? Or maybe also add the time period? so "120 lakes predicted to support bass in late century"?

**Comment by jordansread** [comment]
Somehow these changes were lost:
![image](https://cloud.githubusercontent.com/assets/2349007/16687559/0256f884-44df-11e6-8b8f-21b146489c25.png)

tracking that down...

**Comment by jordansread** [comment]
Ok, figured that out and updated the text in #73

**Comment by jordansread** [comment]
in #74 now
