### ISSUE TITLE
section "walleyeDecline" text content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#29]
- Walleye are a preferred species for many anglers, and important to Wisconsin’s economy and culture. 
- Some have hypothesized that largemouth bass are directly responsible for walleye declines. However, evidence to date does not support this claim.

Need @gjahansen2 to propose how this text goes into the viz. Ask bullets? prose?

**Comment by gjahansen2** [comment]
I guess that question applies more broadly to the content of each section of the viz. Do we want prose or bullet points? In any case, the meat of the text for each section needs to be written (by me). My gut feeling is bullet points but I can be persuaded.

Where/how is the best place for me to edit this text? In the google doc or somewhere else in this crazy github world?

**Comment by lawinslow** [comment]
Agreed on bullet points.

**Comment by gjahansen2** [comment]
- Anglers target both walleye and largemouth bass in Wisconsin lakes. 
- Walleye  are preferred by many anglers, and are important to Wisconsin’s economy and culture. 
- Much interest exists in understanding the causes of walleye population declines and whether they can be reversed. 
- There are many possible explanations for the observed changes in Wisconsin lake fish communities.
- Some have hypothesized that largemouth bass are directly responsible for walleye declines. However, evidence to date does not support this claim.

**Comment by jordansread** [comment]
added in #49
