### ISSUE TITLE
section "walleyeBass" text content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#30]
- Temperature is key characteristic determining the suitability of a lake for walleye or largemouth bass.
- Interactive figure drawing the relationship between DD and each species. 
  - Key points:
    Walleye prefer cool water
    LMB prefer warm water
    The relationship for each species shows a threshold response – the shape is flat above and below a certain point. All lakes below a certain temperature threshold are equally suitable for walleye (on average), and all lakes above that threshold are equally unsuitable for walleye (on average). Reverse is true for LMB.
    The relationships between the two species cross – there is a threshold temperature that separates good walleye lakes from good bass lakes.

**Comment by jordansread** [comment]
related to #25

**Comment by gjahansen2** [comment]
Obviously this text is terrible. where do you want me to edit it (google docs or here or somewhere else) and do you like bullet points or prose?

**Comment by jordansread** [comment]
You could just add the preferred text to this issue, and we can get it in from there. Or you could step into the github world...

**Comment by gjahansen2** [comment]
I want to learn!

On Wed, Jun 15, 2016 at 9:38 AM, Jordan S Read notifications@github.com
wrote:

> You could just add the preferred text to this issue, and we can get it in
> from there. Or you could step into the github world...
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/30#issuecomment-226207620,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6hrZ8ZLzaai8hb9Kh9SoLSXrhNZcks5qMA5vgaJpZM4I2Xaj
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
@gjahansen2 you can also add new text keys in there if you want. Such as `walleyeBass-p1` for paragraph 1
or `walleyeBass-bullet-1` for a bullet point

**Comment by jordansread** [comment]
the file is yaml. Info on that: http://www.yaml.org/start.html

**Comment by jordansread** [comment]
Other helpful links: https://guides.github.com/activities/hello-world/#commit

**Comment by gjahansen2** [comment]
- Water temperature is key characteristic determining the suitability of a lake for different species of fish, such as walleye or largemouth bass.

[interactive figure]

[after they draw their figure] 
- In general, walleye naturally reproduce more successfully in cool lakes, and largemouth bass populations are most abundant in warm lakes.
- Cool lakes that are best for walleye are the worst places for largemouth bass. At the same time, the warm lakes that are best for finding high numbers of largemouth bass have the worst conditions for walleye.
- These relationships are averages. Other lake characteristics besides temperature influence the suitability of a lake for each species. For example, walleye can successfully reproduce in Wisconsin's largest lakes even if they are warm.

**Comment by jordansread** [comment]
added in #49
