### ISSUE TITLE
capture data fetch and processing for "wallyDecline" section figs

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#31]
Currently this is ad-hoc, but we need to host the data on SB, pull it down w/ a fetch and process it into the format we need for visualize.

**Comment by jordansread** [comment]
1) create SB community for this viz (like we did with microplastics)
2) host raw data on SB 
3) modify viz.yaml to include the SB keys, file names, etc
4) write a process script to convert the data into the figure inputs

**Comment by jordansread** [comment]
Currently, fetch, process, and visualize are all garbled up together: https://github.com/USGS-VIZLAB/climate-fish-habitat/blob/master/scripts/2_munge/munge_bass_wally_decline.R

**Comment by lindsayplatt** [comment]
- [x] create SB community for this viz: [new folder in VizLab community](https://www.sciencebase.gov/catalog/item/5761775ae4b04f417c2d2f78?community=Visualization+Laboratory)
- [x] host raw data on SB 
- [x] modify viz.yaml to include the SB keys, file names, etc
- [x] write a process script to convert the data into the figure inputs

**Comment by lindsayplatt** [comment]
do we want a munge.yaml like we had in microplastics viz? https://github.com/USGS-VIZLAB/great-lakes-microplastics/blob/master/munge.yaml

**Comment by lawinslow** [comment]
@jread-usgs and I were thinking about going with just a single munge/visualize step. Unless VIZLAB requires separate steps?

**Comment by lindsayplatt** [comment]
Idk, that would be a @jiwalker-usgs question

**Comment by jordansread** [comment]
No, combining munge and viz was a placeholder while we were working in sandbox. Lindsay is working on teasing out the separate pieces as part of this task

**Comment by jordansread** [comment]
but @lindsaycarr there won't be a munge.yaml to answer your question

**Comment by lindsayplatt** [comment]
@jread-usgs is this good to close?
