### ISSUE TITLE
section "lakeWarming" text content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#32]
- Some lakes have warmed more than others. 
- Lake size, depth, clarity, and tree cover surrounding the lake all influence how much lakes have warmed.

**Comment by gjahansen2** [comment]
- Not all lakes are the same, and they respond differently to climate.
- Some lakes have warmed more than others.
- Some lakes have always been warmer than others - for example, lakes in southern Wisconsin are generally warmer than lakes in northern Wisconsin.
- Lake size and depth, water clarity, and surrounding tree cover all influence how lakes respond to air temperature.
- Differences in temperatures and warming rates affect fish communities in Wisconsin lakes.

**Comment by jordansread** [comment]
added in #49
