### ISSUE TITLE
capture data fetch and processing for "futureSutability" section figs

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#38]
similar to #36 , this is for untangling the "munge" and "visualize" steps in https://github.com/USGS-VIZLAB/climate-fish-habitat/blob/master/scripts/2_munge/sankey_fig.R

**Comment by jordansread** [comment]
@lindsaycarr up for this one too?

**Comment by lindsayplatt** [comment]
- [x] host raw data on SB 
- [x] modify viz.yaml to include the SB keys, file names, etc
- [x] write a process script to convert the data into the figure inputs

**Comment by lindsayplatt** [comment]
@jread-usgs are we calling this `futureSuitability` or `habitatShifts`? Seems like viz.yaml uses both and it's kind of confusing

**Comment by jordansread** [comment]
`futureSutability`

**Comment by lindsayplatt** [comment]
should be :+1: once we merge in #44
