### ISSUE TITLE
draft press release

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#46]
@gjahansen2 assigning this to you, but I had some ideas for key points. 

1) this research predicts a higher number of lakes that supported neither bass or wally to support either in the future (positive note. poorly worded..)
2) wally predicted to continue to decline
3) Even w/ the most extreme warming scenario, some walleye lakes are resilient

**Comment by jordansread** [comment]
@gjahansen2 should we iterate on an outline for this?

**Comment by gjahansen2** [comment]
Yes, sorry for the delay. I need to check with supervisors at both WDNR and MNDNR if there is a protocol I need to follow.
Can I share the data vis development site with my supervisor here? With the knowledge that it is in draft form?

**Comment by jordansread** [comment]
@gjahansen2 yes you can share w/ supervisors

**Comment by jordansread** [comment]
Draft is done. Working w/ office of com for edits.
