### ISSUE TITLE
make it so the mobile view of the app still displays figures

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#48]
mobile scales down but the images don't get small enough:

![image](https://cloud.githubusercontent.com/assets/2349007/16244120/308176b6-37c0-11e6-9e48-4a4a949ff74a.png)

**Comment by mwernimont** [comment]
@jread-usgs  this should fix it #56

**Comment by jordansread** [comment]
Still same issue. Got a screen shot of what you are seeing?

**Comment by mwernimont** [comment]
![screen shot 2016-06-23 at 7 40 59 am](https://cloud.githubusercontent.com/assets/6390096/16303367/e24e3194-3915-11e6-9ecb-65743fd2c835.png)
![screen shot 2016-06-23 at 7 40 44 am](https://cloud.githubusercontent.com/assets/6390096/16303380/e9e08a42-3915-11e6-949b-758268f97d77.png)
![screen shot 2016-06-23 at 7 40 52 am](https://cloud.githubusercontent.com/assets/6390096/16303382/ec5dc56e-3915-11e6-8ce0-bbb6f857ac16.png)

**Comment by mwernimont** [comment]
@jread-usgs What I see on smaller screens

**Comment by jordansread** [comment]
fixed
