### ISSUE TITLE
user experience for temperature preference figure

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#5]
![image](https://cloud.githubusercontent.com/assets/2349007/15557506/04547dc2-2299-11e6-84d1-cc896a5929aa.png)

talked about this one w/ Luke.

The key message here is that there are different thermal guilds for the different species of interest. We'll have the user make a guess as to where the three (?) species' ideal thermal range is and then have them  lock in those choices and reveal the reality. Inspired by http://www.nytimes.com/interactive/2015/05/28/upshot/you-draw-it-how-family-income-affects-childrens-college-chances.html 

After the three are locked in and "I'm done" is chosen, we do a one by one adjustment with text to accompany "you chose 63°F for Lake Trout, that is too warm. Lake Trout prefer X-Y°F" 

User can select "reset" to start it again.

If user scrolls past both trigger points (one for making it appear, the other makes them all move) the fish move to the right place. 

I assume all this will be fine on mobile w/ drag features, but likely won't work on IE.

**Comment by lawinslow** [comment]
Only thought on this is do you need an "i'm done" button, or can that automatically be triggered when the third fish is placed?

**Comment by jordansread** [comment]
yeah, I think it could work well that way, but I wanted to keep it so you could still move the fish around after you drop them.

**Comment by jordansread** [comment]
I think we are dropping this fig.
