### ISSUE TITLE
section "futureWarming" text content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#50]
![image](https://cloud.githubusercontent.com/assets/2349007/16245123/fe8b5604-37c4-11e6-80ae-5e4cd32816b9.png)

content as of now ☝️

**Comment by gjahansen2** [comment]
- As air temperatures increase, we expect lake temperatures to increase as well.
- However, not all lakes will respond equally to climate change. 
- The  incredible diversity of lake types in Wisconsin means that we can expect different warming rates in big vs. small lakes, deep vs. shallow lakes, clear vs. turbid lakes. 
- Understanding differences among lakes in their responses to climate change is a high priority for managing fish populations that are sensitive to warming temperatures.
