### ISSUE TITLE
section "futureSuitability" text content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#51]
content as of now:
![image](https://cloud.githubusercontent.com/assets/2349007/16245163/2fdef33c-37c5-11e6-82d2-aa391e1c9431.png)

**Comment by gjahansen2** [comment]
![millelacs_sun_boats](https://cloud.githubusercontent.com/assets/19436778/16420173/00120b98-3d16-11e6-9d41-00479ba5435b.jpg)

**Comment by gjahansen2** [comment]
^^potential new picture?

**Comment by jordansread** [comment]
as background, or as a pic within the section? I like it. Milacs?

**Comment by gjahansen2** [comment]
Probably background. The picture of Jon with both species could be a picture within the section if there is room. This is Mille Lacs, yes

**Comment by jordansread** [comment]
ok, can you email me the full res version?

**Comment by gjahansen2** [comment]
emailed

**Comment by gjahansen2** [comment]
See comments on fish management section, I think that is the better place for the new picture and the picture of Jon. 
Text for this section:
- As water temperatures warm, many present-day walleye lakes will transition into largemouth bass lakes.
- The majority of Wisconsin lakes lakes are expected to contain high density largemouth bass populations by the mid-21st century. 
- A small percentage of lakes will continue to support both species into the future.

**Comment by jordansread** [comment]
where do we use the pic of Ada ;) ?

**Comment by gjahansen2** [comment]
Oh yeah, we definitely need that in there too.

On Tue, Jun 28, 2016 at 10:17 AM, Jordan S Read notifications@github.com
wrote:

> where do we use the pic of Ada ;) ?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/51#issuecomment-229081954,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6vdRnCPgYrf-oXCP4Nzu-6mt0QRXks5qQTsZgaJpZM4I7JDo
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
@gjahansen2 
`See comments on fish management section, I think that is the better place for the new picture and the picture of Jon.`
I am confused, I thought this new pic was to replace the pic of Jon as the background of this section (futureSuitability), do you want it to be used in the `fishManagement` section (the one that follows this section) instead? If so, what picture would be used as the background for this section if we use Jon's pic as an inset in that section?

**Comment by jordansread** [comment]
Am not a big fan of the styling of the bullets, but we can change that later. Is this what you had in mind @gjahansen2 ?
![image](https://cloud.githubusercontent.com/assets/2349007/16457721/1bef0b78-3de2-11e6-9bc6-1b39242517c0.png)

**Comment by gjahansen2** [comment]
lakes is repeated in the second bullet (Wisconsin lakes lakes).
I don't like the font/styling either but we can deal later.

On Wed, Jun 29, 2016 at 10:13 AM, Jordan S Read notifications@github.com
wrote:

> Am not a big fan of the styling of the bullets, but we can change that
> later. Is this what you had in mind @gjahansen2
> https://github.com/gjahansen2 ?
> [image: image]
> https://cloud.githubusercontent.com/assets/2349007/16457721/1bef0b78-3de2-11e6-9bc6-1b39242517c0.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/51#issuecomment-229388105,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6s66TbLG4o9-qpCYb1UGA_owd9miks5qQouUgaJpZM4I7JDo
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com
