### ISSUE TITLE
section "fishManagement" text content

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#52]
![image](https://cloud.githubusercontent.com/assets/2349007/16245192/4ba6b532-37c5-11e6-823c-2110313c1c17.png)

**Comment by gjahansen2** [comment]
- Nearly 100 lakes in Wisconsin are predicted to support naturally reproducing walleye populations even under extreme warming conditions.
- These  lakes are resilient to climate change, and should be protected from other stressors such as habitat loss, invasive species, or overfishing to maximize the potential for continued walleye production.
- Some lakes that are unlikely to  support natural walleye reproduction will continue to be suitable for adult walleye, and fishable walleye populations could potentially be maintained in these lakes via stocking.
- Quality fishing opportunities for largemouth bass and other warm water species will be possible in lakes that become unsuitable for walleye.

**Comment by gjahansen2** [comment]
Actually, the picture of Jon with both fish should be here, I think.

**Comment by gjahansen2** [comment]
And maybe the Mille Lacs background picture should be on this one too. I was confusing the two sections.

**Comment by jordansread** [comment]
OK, just saw these comments, so you can ignore my questions on the other issue about background pictures

**Comment by jordansread** [comment]
Pic of jon w/ fish and pic of Ada w/ bass in this section? might make sense since the "coexist" and "bass dominated" are two of the bright spots coming out of this section.

**Comment by gjahansen2** [comment]
Sounds fine, then I guess the new Mille Lacs pic in the other section? Maybe it is best to just work it up however you think it works best, then comment and change as needed.

**Comment by jordansread** [comment]
Have added the text, but we should deal with the organization of pictures and backgrounds as a separate issue
