### ISSUE TITLE
welcome text

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#61]
or have none. 

Currently, 
![image](https://cloud.githubusercontent.com/assets/2349007/16458633/63b7ff3e-3de5-11e6-96cf-4f4d339cd6bf.png)

Here is what we did for microplastics (still in progress with the social media icons):
![image](https://cloud.githubusercontent.com/assets/2349007/16458653/7584e9de-3de5-11e6-8247-f26faaf82ec0.png)

**Comment by jordansread** [comment]
@gjahansen2 got any goodies or suggestions for this?

**Comment by gjahansen2** [comment]
# Climate change and freshwater fish

## Lakes in Wisconsin are getting warmer, and fish communities are changing as a result.

### Understanding recent trends and anticipating future changes can help decision-makers protect resilient populations and adapt to new conditions.

**Comment by gjahansen2** [comment]
mic drop. I am headed north for the weekend.

**Comment by jordansread** [comment]
GH is suggesting changing this to:

![image](https://cloud.githubusercontent.com/assets/2349007/16591885/a7be5828-42a3-11e6-9927-42b9c1be2559.png)

**Comment by gjahansen2** [comment]
And then there could be the white space with the last piece of text ("understanding..." above) to separate this picture from the next.

**Comment by jordansread** [comment]
desktop:
![image](https://cloud.githubusercontent.com/assets/2349007/16687443/48515e70-44de-11e6-9fb4-b8a1d57bc47e.png)

mobile:
![image](https://cloud.githubusercontent.com/assets/2349007/16687451/56ab4de6-44de-11e6-95a9-8160cff16f9d.png)

we probably want to do a little tweaking on parts of how that last piece works, but I think this update covers this issue. Agree @gjahansen2 ?

**Comment by gjahansen2** [comment]
Yes. but change last text section to read as above: 

## Understanding recent trends and anticipating future changes can help decision-makers protect resilient populations and adapt to new conditions.

**Comment by jordansread** [comment]
fixed in #73
