### ISSUE TITLE
improve style of text sections

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#64]
Bullet points and default `<p>` text is a bit bland. 

Can someone take the reins on some design suggestions?

**Comment by jordansread** [comment]
@gjahansen2 please weigh in here with suggestions

**Comment by gjahansen2** [comment]
Text needs to be much, much larger.
Bullets could be a more interesting shape than filled black circle - even an open circle would probably look better, or maybe a ‣

**Comment by jordansread** [comment]
fixed in #65
