### ISSUE TITLE
style updates

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#67]
- [x] change theme color on header. The blue doesn't quite fit
- [x] create mobile image swap ins (create the pattern for one and I can follow it for others)
- [x] create a figure caption class (kind of like on Lower CO river drought app)
- [x] add support for inline photo (see below)
- [ ] ~~make footer color match header color~~

**Comment by jordansread** [comment]
@mwernimont can you add a slightly different color to the caption class (the background color)?

**Comment by jordansread** [comment]
for the forth box:
![image](https://cloud.githubusercontent.com/assets/2349007/16630254/3fbd4856-437f-11e6-8165-b18e77600adb.png)

**Comment by mwernimont** [comment]
Something not right?

**Comment by jordansread** [comment]
oh, this is for the forth check box - a class that supports a smaller pic used in the app, such as the paste thing I put in there.

**Comment by jordansread** [comment]
@mwernimont see above for footer color

**Comment by jordansread** [comment]
all good
