### ISSUE TITLE
draw expected pattern for temperature and probability of wally/bass

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#7]
@gjahansen2 need data for GDD figure, Jordan will add "drawing" experience

**Comment by gjahansen2** [comment]
what kind of data do you need? The current figure is median with interquartile range. I could give you that or raw numbers.

**Comment by jordansread** [comment]
Raw data please

**Comment by gjahansen2** [comment]
@jread-usgs 
Data for both species here:
https://drive.google.com/open?id=0BwCnuHTL_uP9NXZnOTZEVHdUMGM 
partial_plot_LMB_GDD_median_quartiles.csv
partial_plot_wae_GDD_median_quartiles.csv

**Comment by jordansread** [comment]
@gjahansen2 here is what this looks like now:

![image](https://cloud.githubusercontent.com/assets/2349007/15803025/089b1ed8-2a8f-11e6-9240-c1d799131125.png)

**Comment by gjahansen2** [comment]
Cool. Can we lose the dots and make the 'cooler lakes' and 'warmer lakes' labels bigger?

**Comment by jordansread** [comment]
The dots go away when you click "finished", but I like to keep them there before that to show that you can still edit it. That OK?

**Comment by jordansread** [comment]
initial view:
![image](https://cloud.githubusercontent.com/assets/2349007/16045177/f3c48258-320c-11e6-9508-134e1489ed14.png)

incomplete draw:
![image](https://cloud.githubusercontent.com/assets/2349007/16045196/0ee80d20-320d-11e6-8332-4cb0316b40e5.png)

complete draw:

![image](https://cloud.githubusercontent.com/assets/2349007/16045208/1bc0f9bc-320d-11e6-8c9d-dcf1a9c5a0f6.png)

fold out to reality:
![image](https://cloud.githubusercontent.com/assets/2349007/16045221/26aeecbc-320d-11e6-93f6-bfb4212af064.png)

(but I want to change the way this end view works). 

@gjahansen2

**Comment by gjahansen2** [comment]
Ok, so is the end view going to show both what the user drew and the true relationship?

**Comment by jordansread** [comment]
yes, currently the bottom part of it "folds out" to the real view. I was thinking your drawing up top would become more transparent, it it would overlay your guess on the real data while explaining it. Something like that, but we probably want to iterate.

**Comment by jordansread** [comment]
see #25
