### ISSUE TITLE
Updates to futureSuitability figure

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#74]
Initial work was done in #28. This issue covers improvements to that figure. 
- [x] improve tooltips. They are kind of herky-jerky in switching from right to left justified when the words are too long (right side of the fig). Plus, it might make sense to do some line wrapping so the tips aren't too long.
- [x] flip the order of some of the "flows" so that the skinnier lines are always on top of the bigger ones (see example below)
- [x] make a mobile version that is easier to read the text

want that skinnier line to be on top:
![image](https://cloud.githubusercontent.com/assets/2349007/16696624/65c69f4c-450b-11e6-8406-d18ec32237d3.png)

**Comment by jordansread** [comment]
@gjahansen2 think we can manage removing some of the labels on the really small slices? 
![image](https://cloud.githubusercontent.com/assets/2349007/16698720/4a65c5e8-4515-11e6-9a02-9ffb646c45e0.png)

trying to make this easy to read on mobile and smaller comp screens. 

Note that the mouseovers still work

**Comment by gjahansen2** [comment]
I think people might wonder about them if we did that. Can you remove them
just on mobile but leave them on the desktop version?

On Fri, Jul 8, 2016 at 2:07 PM, Jordan S Read notifications@github.com
wrote:

> @gjahansen2 https://github.com/gjahansen2 think we can manage removing
> some of the labels on the really small slices?
> [image: image]
> https://cloud.githubusercontent.com/assets/2349007/16698720/4a65c5e8-4515-11e6-9a02-9ffb646c45e0.png
> 
> trying to make this easy to read on mobile and smaller comp screens
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/74#issuecomment-231446665,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6lKC8II94Yeg47W14eCB_X5a-Ocuks5qTp_6gaJpZM4JIQUM
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
yes, we can do that. I am leaving the line of code that adds those in there, just commented out. For the time being I want to try leaving out those small labels for desktop too just so we can see how we feel (this isn't yet updated on dev), but we can easily add them back.

**Comment by jordansread** [comment]
Finished w/ #78

**Comment by jread-usgs** [comment]
@

**Comment by jordansread** [comment]
@gjahansen2 can you add your `lose` and `gain` text here?

**Comment by gjahansen2** [comment]
OK, I will write out each one that needs to be changed. If it is not listed here, leave it as is. :
- [x] Walleye to coexist: X lakes gain largemouth bass
- [x] Walleye to bass: X lakes lose walleye and gain largemouth bass
- [x] Walleye to neither: X lakes lose walleye
- [x] Coexist to bass: X lakes lose walleye
- [x] Coexist to coexist: X lakes continue to support both species
- [x] **NOTE that the mouse-over label for Coexist currently contains the word "BALLEYE" in the description for all 3 purple boxes.
- [x] Bass to coexist: X lakes gain walleye
- [x] Bass to neither: X lakes lose bass
- [x] Neither to walleye: X lakes gain walleye
- [x] Neither to bass: X lakes gain bass
- [x] Neither to neither: X lakes continue to support neither species

This is the simple version of the text. Possible additions include:
- listing  the current state for each transition. For example, for walleye to coexist, instead write "X walleye dominant lakes gain largemouth bass."
- Incorporating the words "are predicted to". For example, "X lakes are predicted to gain largemouth bass"
- Using more precise language regarding each species. For example, "X lakes are predicted to gain the ability to support high largemouth bass abundance".

Components of each of these are scattered throughout, currently. Each one makes it a bit longer, so I think I prefer the simplest version as listed above. People will be able to see what class the lakes are moving from, and I hope it is clear that these are predictions (not statements of certain fact), although we should probably be explicit on that somewhere. For the last point, I would prefer to use the precise language, but if we describe each class in the caption maybe we can get away with it.
