### ISSUE TITLE
Updates to walleyeBass figure

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#76]
takes over from #25 
- [ ] ~~change bass values to be more intuitive rather than standardized relative abundance (Gretchen will send new data)~~ moved to #128 
- [x] lock in bass values so the user only edits walleye
- [ ] ~~script the creation of this fig (is hand-edited `svg` now)~~
- [x] fix FF roll out bug ~~fixed in #98~~
- [x] add a legend
- [x] cut down on the amount of text we use to "draw the pattern" helpers
- [x] overlay user result onto actual trend fig
- [ ] ~~caption should appear after you draw~~
- [x] add user guess callout
- [ ] ~~figure should complete itself if user scrolls past it~~ `skip ahead` button instead
- [ ] ~~pop the result text out after completion~~ too complicated
- [x] send user guesses to google analytics? (is this possible?)

```
https://developers.google.com/analytics/devguides/collection/analyticsjs/events
```

**Comment by jordansread** [comment]
Legend not in place, but user data overlay from #79 :
![image](https://cloud.githubusercontent.com/assets/2349007/16718220/99cb9642-46e3-11e6-8f39-44952b4ee161.png)

**Comment by jordansread** [comment]
@gjahansen2 can you add your ideas for the feedback the figure should give you for your guess?

**Comment by gjahansen2** [comment]
The predicted probability of successful walleye recruitment declines as lakes get warmer. This decline is not linear. Instead, we observe a strong threshold response. This means that the probability of successful walleye recruitment is approximately constant up to a certain value of water temperature (about 2400 growing degree days, at which point the probability of natural walleye recruitment declines rapidly, then levels off again. The threshold water temperature value where walleye recruitment becomes much less likely corresponds to the same value where the probability of observing high largemouth bass abundance  becomes much higher, suggesting that both species are responding to similar temperature cues, but in opposite directions.

**Comment by gjahansen2** [comment]
Can we make the above text pop out in some way after the drawing is done, like in a text box, different color, font, etc?

**Comment by jordansread** [comment]
figure out how to get the roll-out to work properly on firefox (mac only?)
![image](https://cloud.githubusercontent.com/assets/2349007/17282335/660fcf52-576a-11e6-8431-5d52cff5e185.png)

**Comment by gjahansen2** [comment]
Note the additional item as checkbox - change bass values to be on a more intuitive scale. I am working on it. @jread-usgs
