### ISSUE TITLE
parallax image backgrounds into framework

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#8]
similar to https://www.doi.gov/water/owdi.cr.drought/en

**Comment by jordansread** [comment]
![image](https://cloud.githubusercontent.com/assets/2349007/15791066/cf0aa7d2-299a-11e6-8cb2-88ca0e8fa168.png)

and more pics @gjahansen2

**Comment by jordansread** [comment]
@jread-usgs add folder pics into repo

**Comment by mwernimont** [comment]
@jread-usgs Was this accomplished or am still missing something?

**Comment by jordansread** [comment]
done
