### ISSUE TITLE
text for captions

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#80]

**Comment by gjahansen2** [comment]
Figure 1 (trends over time): Statewide average values over time for walleye recruitment (blue; indexed as catch of age-0 walleye per mile of electrofishing) and largemouth bass relative abundance (red; indexed as catch of largemouth bass greater than 8 inches in length per mile of electrofishing, presented on a standardized scale). Dashed lines show overall directional trend over time.

Figure 2 (you draw it figure, caption only shows up with completed figure):  Predicted probability of a lake supporting successful walleye recruitment and high largemouth bass abundance as a function of water temperature (degree days). Probabilities are based on a statistical model that incorporates other lake characteristics such as water clarity and lake size. Different values of these other variables will affect lake specific probabilities - the lines here show averages.

Figure 3 (map of WI with contemporary trends) - Skipping for now 

Figure 4 (increasing air temperatures).  I think @jread-usgs or @lawinslow should write this one

Figure 5 (Sankey): Number of lakes classified by predicted species dominance under contemporary (1989-2014), mid-century future (2040-2064), and late-century future (2065-2089) conditions. Lakes are classified based on their predicted probabilities of walleye recruitment and largemouth bass relative abundance. Classes are defined as: walleye dominant (blue; walleye recruitment success and low largemouth bass relative abundance), coexistence (purple; walleye recruitment success and high largemouth bass relative abundance), largemouth bass dominant (orange; walleye recruitment failure and low largemouth bass relative abundance), or neither (grey; walleye recruitment failure and low largemouth bass relative abundance).  Colored lines show projected movements among lake classes, and line width is proportional to the number of lakes moving between each class. Numbers are based on median projections across multiple global climate models.

Figure 6 (Picture of lake with sunset): do we need a caption? If yes: a fishing trip on a beautiful midwestern lake.

**Comment by jordansread** [comment]
Great. Very helpful. I will add these

**Comment by gjahansen2** [comment]
As I read it (and work on the text that describes Figure 2 after they make a guess), i think the caption could be there from the get-go. Then, could the response text pop up as some sort of text box or some way to make it really pop?

**Comment by jordansread** [comment]
is the response text the bullets?

**Comment by gjahansen2** [comment]
Yeah, I guess looking at the bullets again, those pretty much cover it. Can
we make them pop a bit more?

On Tue, Jul 12, 2016 at 2:29 PM, Jordan S Read notifications@github.com
wrote:

> is the response text the bullets?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/80#issuecomment-232153449,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASiU6uqwJkRf0A6EAF4wChIA9yM1tfSNks5qU-sLgaJpZM4JKiiZ
> .

## 

Gretchen Hansen
https://gretchenhansen.squarespace.com

**Comment by jordansread** [comment]
yes, I want to make them pop more too

**Comment by jordansread** [comment]
@gjahansen2 can you mock up how you think this should look after it is unfurled?

**Comment by gjahansen2** [comment]
@jread-usgs mock up of which - the you draw it figure with captions and bullets after they submit their guess?

**Comment by jordansread** [comment]
yeah, the bullets and text and how they relate to the figure in terms of placement

**Comment by gjahansen2** [comment]
powerpoint time.

**Comment by gjahansen2** [comment]
![you draw it figure caption pre drawing](https://cloud.githubusercontent.com/assets/19436778/16885066/6abf3fb8-4a92-11e6-8d9d-28f3541527c6.jpg)

**Comment by gjahansen2** [comment]
![you draw it figure caption and pop up post drawing](https://cloud.githubusercontent.com/assets/19436778/16885076/7b77e83c-4a92-11e6-9542-1c91829a9073.jpg)

**Comment by gjahansen2** [comment]
New caption text: 
Predicted probability of a lake supporting successful walleye recruitment and high largemouth bass abundance as a function of water temperature (degree days). Probabilities are based on a statistical model that incorporates other lake characteristics such as water clarity and lake size. 

New bullet text:
- Water temperature influences the suitability of a lake for walleye and largemouth bass
- In general, walleye reproduce more successfully in cooler lakes, and largemouth bass populations are most abundant in warm lakes.
- Both species exhibit a threshold response to temperature, where small changes in temperature can produce big changes in the fish population. 
- The temperature threshold separating lakes with successful vs.unsuccessful walleye reproduction is approximately the same threshold separating lakes with low vs. high largemouth bass abundances.
- This means that lakes that are best for walleye are generally worst for largemouth bass, and vice versa.
- These relationships are averages. Other lake characteristics influence the suitability of the lake for each species. For example, walleye can reproduce successfully in large lakes even if they are warm.

**Comment by jordansread** [comment]
I think this is done now
