### ISSUE TITLE
map for futureSuitability w/ fish categories

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#81]
Under the sankey, build a static map of part of WI, with a click-out to "explore more" as a leaflet map.

click lakes to get probabilities.

**Comment by jordansread** [comment]
Iterating w/ GH on this, but here is the start for the WMS:
![image](https://cloud.githubusercontent.com/assets/2349007/16783728/dbae524e-484a-11e6-8440-9c1fe3779ccf.png)

at https://www.sciencebase.gov/catalog/item/imap/57854d3de4b0e02680bf201d

**Comment by jordansread** [comment]
Iterating with GH and @mhines-usgs on this. Megan created the fiddle:  http://jsfiddle.net/mkhines/m8q1xs19/

Ultimately, what we would like to do here is 
- [x] host three different WMSs for the three different periods (jordan will do this; see #83 
- [x] create a radio button to toggle between time periods (toggle between those layers). Force the user to have == one selected at all times
- [x] on click of a feature, we bring back a tool tip that has a filtered subset of the attributes come back (assuming we can alter that css when the attributes are locked in)
- [x] include a legend (like what we have in the screen-cap)
- [x] use `CartoDB.Positron` tiles for the map
- [x] have this be something can wrap up and deploy as part of the viz, but as its own "explore more" subpage.

**Comment by mhines-usgs** [comment]
I've got a few of these ticked off, I'll start on the radio toggle/layer toggle now. May just use other irrelevant layers until you have the other WMSs ready. Let me know any feedback on what is ticked.

**Comment by mhines-usgs** [comment]
Re: the legend @jread-usgs , I'm using the legend graphic coming from ScienceBase WMS getCaps. If you want a No Data swatch, you should have one in the original shapefile/layer so that it'll feed in from there. Is that possible?

**Comment by mhines-usgs** [comment]
For the last checkbox (have something that can be wrapped up and deploy as part of the viz)
- You'll have to copy & paste the html/js and css into new files and check into repo.
- You'll also want the leaflet.css, leaflet.js and jquery-1.10.1.min.js files that are "External Resources" in the fiddle currently.
- These will need to be referenced in the html file. make sure the html file also has a div with the id of map.

**Comment by mhines-usgs** [comment]
three layers
1989-2014: 
- https://www.sciencebase.gov/catalog/item/57924eafe4b0fc973c6bcc6d
- https://www.sciencebase.gov/catalogMaps/mapping/ows/57924eafe4b0fc973c6bcc6d?service=wms&request=getcapabilities&version=1.3.0

2040-2064:
- https://www.sciencebase.gov/catalog/item/57924fd3e4b0fc973c6bccdf
- https://www.sciencebase.gov/catalogMaps/mapping/ows/57924fd3e4b0fc973c6bccdf?service=wms&request=getcapabilities&version=1.3.0

2065-2089:
- https://www.sciencebase.gov/catalog/item/57925024e4b0fc973c6bcce3
- https://www.sciencebase.gov/catalogMaps/mapping/ows/57925024e4b0fc973c6bcce3?service=wms

**Comment by mhines-usgs** [comment]
One for all:
https://www.sciencebase.gov/catalogMaps/mapping/ows/57927e39e4b0d02dcaaeed1d?service=wms&request=getcapabilities&version=1.3.0

**Comment by mhines-usgs** [comment]
I think we're good here @jread-usgs !

Do you want me to check files into the repo? Or is someone else prepared to do that? Not sure how you'd like to work it into the viz.

**Comment by jordansread** [comment]
yes, if you can check those files into the `sandbox` dir, we can figure out where @jiwalker-usgs wants them to live when we get that far.

**Comment by jordansread** [comment]
![fishmap-thumbnail](https://cloud.githubusercontent.com/assets/2349007/17071385/e1e3fe64-5026-11e6-84dc-9582c1528e84.gif)

**Comment by jordansread** [comment]
@gjahansen2 ☝️

**Comment by mhines-usgs** [comment]
:heart_eyes:

**Comment by mhines-usgs** [comment]
completed with: https://github.com/USGS-VIZLAB/climate-fish-habitat/pull/86
