### ISSUE TITLE
Create chapter headers and provide pictures

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#9]
similar to https://www.doi.gov/water/owdi.cr.drought/en/index.html#StorageCapacity @gjahansen2

**Comment by gjahansen2** [comment]
@jread-usgs @lawinslow 
You can find my initial ideas here: https://drive.google.com/open?id=0BwCnuHTL_uP9VUF0NWdPRGs4eUU
I would like feedback on the pictures and the chapter headers themselves. I also provided a few bullet points regarding content.

**Comment by jordansread** [comment]
These are really good! I think we should start with these are the defaults and see how things look together. Read: we will go with this and re-assess when we see the content start to fill in on the prototype site.

**Comment by gjahansen2** [comment]
Pics are here: https://drive.google.com/folderview?id=0BwCnuHTL_uP9NnRlQm1tZTUwUEk&usp=sharing plus a couple more

**Comment by jordansread** [comment]
Calling this done for the time being. Pics are in and headings are in place.

**Comment by gjahansen2** [comment]
@jread-usgs can I see it?
