### ISSUE TITLE
adjustments to mobile CSS

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#90]
mobile figure captions should have about half the font size they have now:

![image](https://cloud.githubusercontent.com/assets/2349007/17143490/09db43e2-5319-11e6-8f3c-2112565e9ee9.png)

bullet points in the list sections are a good size for desktop, but are too large for mobile. Reduce by about 25% if possible.

**Comment by mwernimont** [comment]
![screen shot 2016-07-26 at 10 17 39 am](https://cloud.githubusercontent.com/assets/6390096/17143805/3ae5e464-531a-11e6-9fcd-a12a62db19eb.png)

@jread-usgs Smaller or good?

**Comment by mwernimont** [comment]
![screen shot 2016-07-26 at 10 18 36 am](https://cloud.githubusercontent.com/assets/6390096/17143837/5a7e32fe-531a-11e6-879f-e9d02dd27f2f.png)

**Comment by mwernimont** [comment]
![screen shot 2016-07-26 at 10 21 02 am](https://cloud.githubusercontent.com/assets/6390096/17143934/b22b3f74-531a-11e6-8442-29331ede9a52.png)

**Comment by jordansread** [comment]
bullets look good, but captions seem too big (also, can they be centered?)

**Comment by mwernimont** [comment]
@jread-usgs on just mobile or both for centered?

**Comment by jordansread** [comment]
Centered for all please @mwernimont

**Comment by mwernimont** [comment]
@jread-usgs #91 is merged, I centered the caption text and reduced it to .9em, it is 1.5em on desktop, so its a significant down size which does look nice on mobile/

**Comment by jordansread** [comment]
thanks @mwernimont !
